use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=cmake/llama-build-overrides.cmake");

    if !cfg!(feature = "android-dynamic-backends")
        || std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("android")
    {
        return;
    }

    // DEP_LLAMA_BACKENDS_DIR is generated by llama-cpp-sys-2
    let backends_dir = PathBuf::from(std::env::var("DEP_LLAMA_BACKENDS_DIR").unwrap());
    let llama_dir = backends_dir.parent().unwrap();
    let library_dir = [llama_dir.join("lib"), llama_dir.join("lib64")]
        .into_iter()
        .find(|path| path.is_dir())
        .expect("llama library directory");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let profile = std::env::var("PROFILE").unwrap();
    let runtime_dir = out_dir
        .ancestors()
        .find(|path| path.ends_with(&profile))
        .expect("Cargo profile directory")
        .join("nobodywho-runtime");
    if runtime_dir.exists() {
        std::fs::remove_dir_all(&runtime_dir).unwrap();
    }
    std::fs::create_dir(&runtime_dir).unwrap();

    copy_shared_libraries(&library_dir, &runtime_dir);
    let backend_names = copy_shared_libraries(&backends_dir, &runtime_dir);
    let cpu_backend_names = backend_names
        .into_iter()
        .filter(|name| name.starts_with("libggml-cpu"))
        .collect::<Vec<_>>();
    assert!(!cpu_backend_names.is_empty(), "no GGML CPU backends built");
    println!(
        "cargo:rustc-env=NOBODYWHO_ANDROID_CPU_BACKENDS={}",
        cpu_backend_names.join(":")
    );

    let output = cc::Build::new()
        .cpp(true)
        .get_compiler()
        .to_command()
        .arg("--print-file-name=libc++_shared.so")
        .output()
        .expect("locating libc++_shared.so");
    assert!(output.status.success(), "locating libc++_shared.so failed");

    let path = PathBuf::from(String::from_utf8(output.stdout).unwrap().trim());
    assert!(path.is_file(), "{} does not exist", path.display());
    std::fs::copy(&path, runtime_dir.join("libc++_shared.so")).unwrap();
}

fn copy_shared_libraries(source: &Path, destination: &Path) -> Vec<String> {
    let mut names = std::fs::read_dir(source)
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.is_file() && path.extension().is_some_and(|ext| ext == "so"))
        .map(|path| {
            let name = path.file_name().unwrap().to_str().unwrap().to_owned();
            std::fs::copy(&path, destination.join(&name)).unwrap();
            name
        })
        .collect::<Vec<_>>();
    names.sort();
    names
}
