// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dart_function_type_to_json_schema`

NobodyWhoTool newToolImpl({
  required FutureOr<String> Function(String) function,
  required String name,
  required String description,
  required String runtimeType,
}) => RustLib.instance.api.crateApiNobodywhoNewToolImpl(
  function: function,
  name: name,
  description: description,
  runtimeType: runtimeType,
);

void initDebugLog() => RustLib.instance.api.crateApiNobodywhoInitDebugLog();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NobodyWhoChat>>
abstract class NobodyWhoChat implements RustOpaqueInterface {
  Stream<String> ask({required String message});

  factory NobodyWhoChat({
    required NobodyWhoModel model,
    required String systemPrompt,
    required int contextSize,
    required List<NobodyWhoTool> tools,
  }) => RustLib.instance.api.crateApiNobodywhoNobodyWhoChatNew(
    model: model,
    systemPrompt: systemPrompt,
    contextSize: contextSize,
    tools: tools,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NobodyWhoModel>>
abstract class NobodyWhoModel implements RustOpaqueInterface {
  factory NobodyWhoModel({required String modelPath, bool useGpu = true}) =>
      RustLib.instance.api.crateApiNobodywhoNobodyWhoModelNew(
        modelPath: modelPath,
        useGpu: useGpu,
      );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NobodyWhoTool>>
abstract class NobodyWhoTool implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Rust2DartSendError>>
abstract class Rust2DartSendError implements RustOpaqueInterface {}
