// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dart_function_type_to_json_schema`

NobodyWhoTool newToolImpl({
  required FutureOr<String> Function(String) function,
  required String name,
  required String description,
  required String runtimeType,
}) => RustLib.instance.api.crateApiNobodywhoNewToolImpl(
  function: function,
  name: name,
  description: description,
  runtimeType: runtimeType,
);

void initDebugLog() => RustLib.instance.api.crateApiNobodywhoInitDebugLog();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< CompletionError>>
abstract class CompletionError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CrossEncoder>>
abstract class CrossEncoder implements RustOpaqueInterface {
  factory CrossEncoder({required NobodyWhoModel model, int nCtx = 4096}) =>
      RustLib.instance.api.crateApiNobodywhoCrossEncoderNew(
        model: model,
        nCtx: nCtx,
      );

  Future<Float32List> rank({
    required String query,
    required List<String> documents,
  });

  Future<List<(String, double)>> rankAndSort({
    required String query,
    required List<String> documents,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< CrossEncoderWorkerError>>
abstract class CrossEncoderWorkerError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Encoder>>
abstract class Encoder implements RustOpaqueInterface {
  Future<Float32List> encode({required String text});

  factory Encoder({required NobodyWhoModel model, int nCtx = 4096}) => RustLib
      .instance
      .api
      .crateApiNobodywhoEncoderNew(model: model, nCtx: nCtx);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< EncoderWorkerError>>
abstract class EncoderWorkerError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< GetterError>>
abstract class GetterError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Message>>
abstract class Message implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NobodyWhoChat>>
abstract class NobodyWhoChat implements RustOpaqueInterface {
  NobodyWhoTokenStream ask({required String message});

  /// Create chat directly from a model path
  static NobodyWhoChat fromPath({
    required String modelPath,
    required String systemPrompt,
    required int contextSize,
    required List<NobodyWhoTool> tools,
    bool useGpu = true,
  }) => RustLib.instance.api.crateApiNobodywhoNobodyWhoChatFromPath(
    modelPath: modelPath,
    systemPrompt: systemPrompt,
    contextSize: contextSize,
    tools: tools,
    useGpu: useGpu,
  );

  Future<List<Message>> getChatHistory();

  /// Create chat from existing model
  factory NobodyWhoChat({
    required NobodyWhoModel model,
    required String systemPrompt,
    required int contextSize,
    required List<NobodyWhoTool> tools,
  }) => RustLib.instance.api.crateApiNobodywhoNobodyWhoChatNew(
    model: model,
    systemPrompt: systemPrompt,
    contextSize: contextSize,
    tools: tools,
  );

  Future<void> resetContext({
    required String systemPrompt,
    required List<NobodyWhoTool> tools,
  });

  Future<void> resetHistory();

  Future<void> setAllowThinking({required bool allowThinking});

  Future<void> setChatHistory({required List<Message> messages});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NobodyWhoModel>>
abstract class NobodyWhoModel implements RustOpaqueInterface {
  factory NobodyWhoModel({required String modelPath, bool useGpu = true}) =>
      RustLib.instance.api.crateApiNobodywhoNobodyWhoModelNew(
        modelPath: modelPath,
        useGpu: useGpu,
      );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NobodyWhoTokenStream>>
abstract class NobodyWhoTokenStream implements RustOpaqueInterface {
  Future<String> completed();

  Stream<String> iter();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NobodyWhoTool>>
abstract class NobodyWhoTool implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Rust2DartSendError>>
abstract class Rust2DartSendError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< SetterError>>
abstract class SetterError implements RustOpaqueInterface {}
