// Generated by uniffi-bindgen-react-native
#include "react-native-nobodywho.h"
#include "../generated/cpp/nobodywho.hpp"

namespace nobodywho {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeNobodywho::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}