[package]
name = "ggml-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"

[target.'cfg(not(target_os = "macos"))'.dependencies]
llama-cpp-sys-2 = { git = "https://github.com/utilityai/llama-cpp-rs", rev = "bed81ad4ab1a6c904b11d425608e50f976d8ea62" }

[target.'cfg(target_os = "macos")'.dependencies]
llama-cpp-sys-2 = { git = "https://github.com/utilityai/llama-cpp-rs", rev = "bed81ad4ab1a6c904b11d425608e50f976d8ea62", features = ["metal"] }
