class Chat:
    def __new__(cls, /, model: Model, n_ctx: int = 2048, system_prompt: str = "", allow_thinking: bool = True, tools: typing.Any = ..., sampler: SamplerConfig | None = None) -> None: ...
    def send_message(self, /, text: str) -> TokenStream: ...

class CrossEncoder:
    def __new__(cls, /, model: Model, n_ctx: int = 2048) -> None: ...
    def rank(self, /, query: str, documents: typing.Any) -> typing.Any: ...
    def rank_and_sort(self, /, query: str, documents: typing.Any) -> typing.Any: ...
    def rank_and_sort_blocking(self, /, query: str, documents: typing.Any) -> typing.Any: ...
    def rank_blocking(self, /, query: str, documents: typing.Any) -> typing.Any: ...

class Embeddings:
    def __new__(cls, /, model: Model, n_ctx: int = 2048) -> None: ...
    def embed_text(self, /, text: str) -> typing.Any: ...
    def embed_text_blocking(self, /, text: str) -> typing.Any: ...

class Model:
    def __new__(cls, /, model_path: str, use_gpu_if_available: bool = True) -> None: ...

class SamplerBuilder:
    def __new__(cls, /) -> None: ...
    def dist(self, /) -> SamplerConfig: ...
    def dry(self, /, multiplier: float, base: float, allowed_length: int, penalty_last_n: int, seq_breakers: typing.Any) -> SamplerBuilder: ...
    def grammar(self, /, grammar: str, trigger_on: str | None, root: str) -> SamplerBuilder: ...
    def greedy(self, /) -> SamplerConfig: ...
    def min_p(self, /, min_p: float, min_keep: int) -> SamplerBuilder: ...
    def mirostat_v1(self, /, tau: float, eta: float, m: int) -> SamplerConfig: ...
    def mirostat_v2(self, /, tau: float, eta: float) -> SamplerConfig: ...
    def penalties(self, /, penalty_last_n: int, penalty_repeat: float, penalty_freq: float, penalty_present: float) -> SamplerBuilder: ...
    def temperature(self, /, temperature: float) -> SamplerBuilder: ...
    def top_k(self, /, top_k: int) -> SamplerBuilder: ...
    def top_p(self, /, top_p: float, min_keep: int) -> SamplerBuilder: ...
    def typical_p(self, /, typ_p: float, min_keep: int) -> SamplerBuilder: ...
    def xtc(self, /, xtc_probability: float, xtc_threshold: float, min_keep: int) -> SamplerBuilder: ...

class SamplerConfig: ...

class TokenStream:
    def __iter__(self, /) -> TokenStream: ...
    def __next__(self, /) -> typing.Any: ...
    def collect(self, /) -> str: ...
    def collect_blocking(self, /) -> str: ...
    def next_token(self, /) -> typing.Any: ...
    def next_token_blocking(self, /) -> typing.Any: ...

class Tool:
    def __call__(self, /, *args, **kwargs) -> typing.Any: ...

def cosine_similarity(a: typing.Any, b: typing.Any) -> float: ...
def tool(description: str) -> typing.Any: ...
