[package]
name = "unity-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
nobodywho = { path = "../core" }
llama-cpp-2 = { git = "https://github.com/utilityai/llama-cpp-rs.git", rev = "b0d355c" }
