[package]
name = "nobodywho-unity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
memory-stats = "1.2.0"
nobodywho = { path = "../core" }
tokio = "1.44.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
