// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "nobodywho-react-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNativeModuleSpec.h"

@interface NobodywhoReactNative : NSObject <NativeNobodywhoReactNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface NobodywhoReactNative : NSObject <RCTBridgeModule>
#endif

@end