name: nobodywho_dart
description: Dart bindings for NobodyWho
version: 1.0.0
repository: https://github.com/nobodywho-ooo/nobodywho

environment:
  sdk: ^3.9.2

dependencies:
  flutter_rust_bridge: ^2.11.1
  ffi: ^2.1.4

dev_dependencies:
  ffigen: ^19.1.0
  lints: ^6.0.0
  test: ^1.25.6
