import typing

class Chat:
    def __new__(cls, /, model: Model, n_ctx: int = 2048, system_prompt: str = "", allow_thinking: bool = True, tools: list[Tool] = ..., sampler: SamplerConfig | None = None) -> None: ...
    def send_message(self, /, text: str) -> TokenStream: ...

class CrossEncoder:
    def __new__(cls, /, model: Model, n_ctx: int = 2048) -> None: ...
    def rank(self, /, query: str, documents: list[str]) -> list[float]: ...
    def rank_and_sort(self, /, query: str, documents: list[str]) -> list[(str, float)]: ...

class CrossEncoderAsync:
    def __new__(cls, /, model: Model, n_ctx: int = 2048) -> None: ...
    def rank(self, /, query: str, documents: list[str]) -> typing.Awaitable[list[float]]: ...
    def rank_and_sort(self, /, query: str, documents: list[str]) -> typing.Awaitable[list[(str, float)]]: ...

class Encoder:
    def __new__(cls, /, model: Model, n_ctx: int = 2048) -> None: ...
    def encode(self, /, text: str) -> list[float]: ...

class EncoderAsync:
    def __new__(cls, /, model: Model, n_ctx: int = 2048) -> None: ...
    def encode(self, /, text: str) -> typing.Awaitable[list[float]]: ...

class Model:
    def __new__(cls, /, model_path: str, use_gpu_if_available: bool = True) -> None: ...

class SamplerBuilder:
    def __new__(cls, /) -> None: ...
    def dist(self, /) -> SamplerConfig: ...
    def dry(self, /, multiplier: float, base: float, allowed_length: int, penalty_last_n: int, seq_breakers: list[str]) -> SamplerBuilder: ...
    def grammar(self, /, grammar: str, trigger_on: str | None, root: str) -> SamplerBuilder: ...
    def greedy(self, /) -> SamplerConfig: ...
    def min_p(self, /, min_p: float, min_keep: int) -> SamplerBuilder: ...
    def mirostat_v1(self, /, tau: float, eta: float, m: int) -> SamplerConfig: ...
    def mirostat_v2(self, /, tau: float, eta: float) -> SamplerConfig: ...
    def penalties(self, /, penalty_last_n: int, penalty_repeat: float, penalty_freq: float, penalty_present: float) -> SamplerBuilder: ...
    def temperature(self, /, temperature: float) -> SamplerBuilder: ...
    def top_k(self, /, top_k: int) -> SamplerBuilder: ...
    def top_p(self, /, top_p: float, min_keep: int) -> SamplerBuilder: ...
    def typical_p(self, /, typ_p: float, min_keep: int) -> SamplerBuilder: ...
    def xtc(self, /, xtc_probability: float, xtc_threshold: float, min_keep: int) -> SamplerBuilder: ...

class SamplerConfig: ...

class TokenStream:
    def __iter__(self, /) -> TokenStream: ...
    def __next__(self, /) -> typing.Any: ...
    def collect(self, /) -> typing.Awaitable[str]: ...
    def collect_blocking(self, /) -> str: ...
    def next_token(self, /) -> typing.Awaitable[str | None]: ...
    def next_token_blocking(self, /) -> str | None: ...

class Tool:
    def __call__(self, /, *args, **kwargs) -> typing.Any: ...

def cosine_similarity(a: list[float], b: list[float]) -> float: ...
def tool(description: str, params: dict[str, str] | None = None) -> typing.Any: ...
