#!/usr/bin/env bash
# Build nobodywho-js's deployable artifacts under wasm32-unknown-emscripten.
#
# Produces nobodywho/js/pkg-bundler/ with:
#   nobodywho_js.js         — modularized Emscripten loader + library glue
#   nobodywho_js_bg.wasm    — wasm-bindgen processed wasm
#   nobodywho_js.wasm       — same wasm (mirrored under a second name some
#                              consumers expect)
#   library_bindgen.js      — kept around so debugging post-link is easy
#
# Prereqs (see ../README.md for setup details):
#   - walkingeyerobot's emscripten fork at $HOME/emscripten-wbg
#     providing the -sWASM_BINDGEN setting (PR emscripten-core/emscripten#23493).
#   - stock wasm-bindgen-cli 0.2.121 at ~/.cargo/bin/wasm-bindgen — used by
#     em++ as the actual descriptor interpreter, controlled via $EM_WASM_BINDGEN.
#   - $LIBCLANG_PATH pointing at a libclang that bindgen can find (Apple's CLT
#     bin/lib works: /Library/Developer/CommandLineTools/usr/lib).
#   - pkg-bundler/pre.js present — the HEAP_DATA_VIEW lazy-getter shim that
#     emcc's --pre-js flag inlines into the loader's prologue. This file lives
#     in the repo's pkg-bundler/ skeleton because it's hand-written, not
#     regenerated by the build.
#
# Why post-link instead of letting emcc do it all in one shot:
#   rustc invokes em++ for the cdylib link with `-o ...wasm`, which makes
#   em++ emit only the .wasm (no JS loader). To produce the runnable bundle
#   we run em++ a SECOND time in `--post-link` mode against the wasm-bindgen
#   library output (already in emcc's temp dir from the cargo build), with
#   `-sMODULARIZE=1 -sEXPORT_ES6=1` to wrap the loader in a factory function.
#
# Why the sed patches: workarounds for codegen bugs in stock wasm-bindgen-cli
# 0.2.121 when targeting the emscripten module shape:
#   - HEAPX0()/HEAPX() (where X = U8/8/U16/16/U32/32/F32/F64) — wasm-bindgen
#     emits the typed-array getter form used by the bundler target. The "0"
#     suffix comes from wasm-bindgen's identifier mangling for some call
#     sites; others emit without the "0". Emscripten's runtime expects the
#     plain HEAPX globals (no parens, no suffix). Patch both forms across
#     every typed-array variant — adding a new one without its sed line
#     produces a `HEAPX0 is not defined` runtime error the moment a binding
#     takes that array type as an arg or returns it (e.g. cosineSimilarity
#     accepting Vec<f32> needed the HEAPF32 patch). When upstream
#     wasm-bindgen learns to emit Emscripten-shaped globals, drop the
#     substitutions.
#   - Model.__wrap / TokenStream.__wrap / Chat.__wrap — wasm-bindgen's
#     "constructor" attribute generates a static-method call on the bare
#     class. emcc wraps classes onto `Module.*`, so the static-method call
#     needs to be redirected to `Module.Model.__wrap`. Same upstream fix
#     applies. New classes that get returned from Rust as wasm-bindgen
#     wrappers (i.e. constructed via `Ok(Foo { ... })` in Rust) need
#     a sed line added here.
#   - __wbg_terminated_addr / __wbg_called_abort — wasm-bindgen-cli
#     references these inside __wbg_call_guard without declaring them
#     anywhere. Without the `var` hoist Emscripten's JS compiler throws
#     ReferenceError before any user code runs.
#   - extraLibraryFuncs.push(...) — Emscripten's JS library compiler doesn't
#     auto-discover the $-prefixed helpers wasm-bindgen emits via
#     `addToLibrary({ '$foo': ... })`. We grep them out of library_bindgen.js
#     and push them onto extraLibraryFuncs so the JS compiler emits them.
#
# Outputs are in pkg-bundler/ ready for `node js/scripts/emscripten-smoke.mjs`,
# `js/examples/*.mjs`, or an npm publish via build-pkg.sh's package.json
# templating step (which is orthogonal to this script).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")"/../../.. && pwd)"   # repo root
JS_DIR="$ROOT/nobodywho/js"
PKG_DIR="$JS_DIR/pkg-bundler"
TARGET_DIR="$ROOT/nobodywho/target/wasm32-unknown-emscripten/release"

EMSDK_DIR="${EMSDK_DIR:-$HOME/emscripten-wbg}"
EM_CONFIG="${EM_CONFIG:-$EMSDK_DIR/.emscripten}"
# IMPORTANT: must be the patched wasm-bindgen CLI (descriptor-interpreter
# fixes + Emscripten output mode), not stock 0.2.121 from crates.io. Build
# it from the local fork checkout per shell.nix's instructions:
#   ( cd ~/wasm-bindgen && cargo install --path crates/cli \
#       --root /tmp/wbg-patched --locked )
# Using ~/.cargo/bin/wasm-bindgen here silently fails — stock CLI emits
# bundler-shape output instead of library_bindgen.js, and the post-link
# step below errors with "library_bindgen.js not found" while leaving
# pkg-bundler stale.
WASM_BINDGEN_BIN="${EM_WASM_BINDGEN:-/tmp/wbg-patched/bin/wasm-bindgen}"

if [[ ! -x "$EMSDK_DIR/emcc" ]]; then
  echo "error: emcc not found at $EMSDK_DIR/emcc" >&2
  echo "       Set EMSDK_DIR to walkingeyerobot's emscripten fork checkout." >&2
  exit 1
fi
if [[ ! -x "$WASM_BINDGEN_BIN" ]]; then
  echo "error: wasm-bindgen-cli not found at $WASM_BINDGEN_BIN" >&2
  echo "       Build the patched fork (see comment above): cargo install --path crates/cli --root /tmp/wbg-patched --locked, or set EM_WASM_BINDGEN." >&2
  exit 1
fi
# `pre.js` is checked in under scripts/ (the pkg-bundler/ dir is
# gitignored, so the file there is a build-time copy). Copy fresh on
# every build so edits to scripts/pre.js take effect.
mkdir -p "$PKG_DIR"
cp "$JS_DIR/scripts/pre.js" "$PKG_DIR/pre.js"

echo "==> cargo build --target wasm32-unknown-emscripten --release -p nobodywho-js"
rm -rf "$TARGET_DIR"
(
  cd "$ROOT/nobodywho"
  # Set RUSTFLAGS explicitly instead of relying on .cargo/config.toml's
  # [target.wasm32-unknown-emscripten] rustflags. A RUSTFLAGS env var
  # (e.g. CI's `setup-rust-toolchain` sets `-D warnings`) overrides the
  # config.toml target rustflags entirely, which would silently drop the
  # +atomics features and break the shared-memory link. Setting it here
  # makes the build self-contained. Safe: cargo doesn't apply target
  # RUSTFLAGS to host build-scripts when --target differs from the host.
  PATH="$EMSDK_DIR:$HOME/.cargo/bin:/opt/homebrew/bin:$PATH" \
  EM_CONFIG="$EM_CONFIG" \
  EM_WASM_BINDGEN="$WASM_BINDGEN_BIN" \
  LIBCLANG_PATH="${LIBCLANG_PATH:-/Library/Developer/CommandLineTools/usr/lib}" \
  RUSTFLAGS="-C panic=abort -C target-feature=+atomics,+bulk-memory,+mutable-globals" \
  cargo +nightly build --release --target wasm32-unknown-emscripten -p nobodywho-js \
    -Zbuild-std=std,panic_abort
)

echo "==> injecting __wasm_bindgen_emscripten_marker custom section"
# The wasm-bindgen runtime declares the marker via
# `#[link_section = "__wasm_bindgen_emscripten_marker"]` on a `#[used]`
# static. Under `wasm32-unknown-emscripten` the attribute ends up in a
# regular data section instead of a wasm custom section — the symbol is
# preserved but the section is not, so wasm-bindgen-cli never sees the
# marker and falls back to bundler-shape output. The Python script below
# patches the wasm post-link to add a real wasm custom section with the
# expected name, restoring the trigger for OutputMode::Emscripten in
# `cli-support/src/lib.rs:768`.
python3 "$JS_DIR/scripts/inject-emscripten-marker.py" \
  "$TARGET_DIR/nobodywho_js.wasm" \
  "$TARGET_DIR/nobodywho_js.marked.wasm"

echo "==> wasm-bindgen-cli on the marked wasm → library_bindgen.js"
# Doing this manually rather than relying on emcc's `-sWASM_BINDGEN`
# auto-invocation: rustc invokes wasm-ld for the cdylib link directly,
# bypassing emcc's `phase_post_link` where the auto-invocation would
# fire. So `-sWASM_BINDGEN` reaches the linker as a no-op rather than
# triggering wasm-bindgen-cli. Calling wasm-bindgen-cli ourselves with
# the same flags emcc would have used (--keep-lld-exports --keep-debug)
# closes that gap without depending on emcc's auto-invocation working.
BINDGEN_OUT="$TARGET_DIR/bindgen-out"
rm -rf "$BINDGEN_OUT"
mkdir -p "$BINDGEN_OUT"
"$WASM_BINDGEN_BIN" \
  "$TARGET_DIR/nobodywho_js.marked.wasm" \
  --keep-lld-exports \
  --keep-debug \
  --out-dir "$BINDGEN_OUT"

if [[ ! -f "$BINDGEN_OUT/library_bindgen.js" ]]; then
  echo "error: wasm-bindgen-cli did not produce library_bindgen.js." >&2
  echo "       Output dir contents:" >&2
  ls -la "$BINDGEN_OUT" >&2
  echo "       Did the marker injection succeed? Re-check the python step above." >&2
  echo "       wasm-bindgen-cli must be the patched fork (with Emscripten" >&2
  echo "       output mode); stock 0.2.121 from crates.io won't work." >&2
  exit 1
fi
echo "==> using $BINDGEN_OUT/library_bindgen.js"

echo "==> copying artifacts into pkg-bundler/"
mkdir -p "$PKG_DIR"
cp "$BINDGEN_OUT/library_bindgen.js" "$PKG_DIR/library_bindgen.js"
# wasm-bindgen-cli writes a processed wasm next to library_bindgen.js
# under whatever stem name it picks from the input. Find it without
# hard-coding the name, since wasm-bindgen-cli's stem-naming logic has
# changed across versions.
WBG_WASM="$(ls "$BINDGEN_OUT"/*.wasm 2>/dev/null | head -n1)"
if [[ -z "$WBG_WASM" ]]; then
  echo "error: wasm-bindgen-cli produced no .wasm under $BINDGEN_OUT" >&2
  exit 1
fi
cp "$WBG_WASM" "$PKG_DIR/nobodywho_js_bg.wasm"

echo "==> applying sed patches to library_bindgen.js"
# See block comment at top of file for why each substitution is needed.
# IMPORTANT: the HEAP patterns must run in BRE mode (default), where the
# `()` are LITERAL parens to strip. They MUST NOT share a sed invocation
# with the `-E` (ERE) `__wrap` patterns below — under -E, `()` is an empty
# group and `s/HEAPF32()/HEAPF32/g` becomes a no-op, leaving `HEAPF32()`
# which then breaks once emcc wraps it as `(growMemViews(), HEAPF32)()`.
sed -i.bak \
  -e 's/HEAPU80()/HEAPU8/g' \
  -e 's/HEAP320()/HEAP32/g' \
  -e 's/HEAPU8()/HEAPU8/g' \
  -e 's/HEAP32()/HEAP32/g' \
  -e 's/HEAPF320()/HEAPF32/g' \
  -e 's/HEAPF32()/HEAPF32/g' \
  -e 's/HEAPF640()/HEAPF64/g' \
  -e 's/HEAPF64()/HEAPF64/g' \
  -e 's/HEAPU160()/HEAPU16/g' \
  -e 's/HEAPU16()/HEAPU16/g' \
  -e 's/HEAP160()/HEAP16/g' \
  -e 's/HEAP16()/HEAP16/g' \
  -e 's/HEAPU320()/HEAPU32/g' \
  -e 's/HEAPU32()/HEAPU32/g' \
  -e 's/HEAP80()/HEAP8/g' \
  -e 's/HEAP8()/HEAP8/g' \
  "$PKG_DIR/library_bindgen.js"

# Fail loudly if any HEAP getter-call form survived the substitutions above.
# A new wasm-bindgen getter variant would otherwise no-op here and surface as
# "HEAPxx is not defined" at runtime once emcc wraps the leftover call.
heap_leftover=$(grep -noE 'HEAP[A-Za-z0-9_]*\(\)' "$PKG_DIR/library_bindgen.js" || true)
if [[ -n "$heap_leftover" ]]; then
  echo "error: un-stripped HEAP getter-call form(s) — add each to the sed list above:" >&2
  echo "$heap_leftover" | sed 's/^/    /' >&2
  exit 1
fi

# Separate ERE invocation for the __wrap redirects (needs grouping).
sed -i.bak1 -E \
  -e 's/(^|[^A-Za-z_])Model\.__wrap/\1Module.Model.__wrap/g' \
  -e 's/(^|[^A-Za-z_])TokenStream\.__wrap/\1Module.TokenStream.__wrap/g' \
  -e 's/(^|[^A-Za-z_])Chat\.__wrap/\1Module.Chat.__wrap/g' \
  -e 's/(^|[^A-Za-z_])SamplerConfig\.__wrap/\1Module.SamplerConfig.__wrap/g' \
  -e 's/(^|[^A-Za-z_])SamplerBuilder\.__wrap/\1Module.SamplerBuilder.__wrap/g' \
  "$PKG_DIR/library_bindgen.js"

# Fail loudly if any wrapper class's `.__wrap` call wasn't redirected to
# `Module.*`. A new #[wasm_bindgen] class returned by value (constructed via
# `Ok(Foo{..})` or a `-> Self` method) needs its own line above; otherwise
# emcc's Module-scoping leaves a bare `Foo.__wrap` that throws at runtime.
unredirected_wrap=$(grep -oE '[A-Za-z_][A-Za-z0-9_.]*\.__wrap' "$PKG_DIR/library_bindgen.js" | grep -v '^Module\.' | sort -u || true)
if [[ -n "$unredirected_wrap" ]]; then
  echo "error: un-redirected .__wrap call(s) in library_bindgen.js — add a sed line for each class:" >&2
  echo "$unredirected_wrap" | sed 's/^/    /' >&2
  exit 1
fi

# Only needed for wasm-bindgen versions that reference __wbg_terminated_addr /
# __wbg_called_abort inside __wbg_call_guard without declaring them. The
# current 0.2.121 doesn't emit that guard, so this is a guarded no-op; if a
# future version reintroduces it, hoist the vars and confirm the hoist landed.
if grep -q 'function __wbg_call_guard() {' "$PKG_DIR/library_bindgen.js"; then
  sed -i.bak2 \
    's|        function __wbg_call_guard() {$|        var __wbg_terminated_addr; var __wbg_called_abort;\n        function __wbg_call_guard() {|' \
    "$PKG_DIR/library_bindgen.js"
  grep -q 'var __wbg_terminated_addr;' "$PKG_DIR/library_bindgen.js" || {
    echo "error: __wbg_call_guard present but the var-hoist sed didn't apply (pattern drift)." >&2
    exit 1
  }
fi

# wasm-bindgen emits `addToLibrary({ memory: memory || new
# WebAssembly.Memory({...,shared:true}) })` when it sees shared memory.
# Emscripten manages `wasmMemory` itself; the bare `memory` reference
# is undefined in the library scope. Strip the entire addToLibrary
# block that contains the memory line.
python3 -c "
import re, sys
path = sys.argv[1]
text = open(path).read()
text, n = re.subn(r'addToLibrary\(\{\n\s*memory:.*\n\}\);\n*', '', text)
if n == 0:
    sys.stderr.write('error: addToLibrary({ memory: ... }) block not found in '
                     'library_bindgen.js — wasm-bindgen output drifted; the '
                     'undefined-memory strip silently no-oped.\n')
    sys.exit(1)
open(path, 'w').write(text)
" "$PKG_DIR/library_bindgen.js"


echo "==> appending extraLibraryFuncs.push(...) for \$-prefixed helpers"
FUNCS=$(
  grep -oE "'\\\$[a-zA-Z_0-9]+'" "$PKG_DIR/library_bindgen.js" \
    | grep -v '__deps' \
    | sort -u \
    | tr '\n' ',' \
    | sed 's/,$//'
)
if [[ -z "$FUNCS" ]]; then
  echo "warning: no \$-prefixed addToLibrary helpers found — script grep may be stale" >&2
else
  echo "extraLibraryFuncs.push($FUNCS);" >> "$PKG_DIR/library_bindgen.js"
fi
rm -f "$PKG_DIR/library_bindgen.js".bak*

echo "==> em++ --post-link to build nobodywho_js.js"
(
  cd "$PKG_DIR"
  PATH="$EMSDK_DIR:/opt/homebrew/bin:$PATH" \
  EM_CONFIG="$EM_CONFIG" \
  "$EMSDK_DIR/emcc" \
    nobodywho_js_bg.wasm \
    --post-link \
    --js-library library_bindgen.js \
    --pre-js pre.js \
    -sALLOW_MEMORY_GROWTH=1 \
    -sMAXIMUM_MEMORY=4GB \
    -sMODULARIZE=1 \
    -sEXPORT_ES6=1 \
    -sEXPORT_NAME='createNobodyWhoModule' \
    -sEXPORTED_RUNTIME_METHODS=FS,SYSCALLS \
    -sFORCE_FILESYSTEM=1 \
    -lnodefs.js \
    -sERROR_ON_UNDEFINED_SYMBOLS=0 \
    -sINVOKE_RUN=0 \
    -Wno-undefined \
    -O1 \
    -pthread \
    -sPTHREAD_POOL_SIZE=navigator.hardwareConcurrency \
    -sDEFAULT_PTHREAD_STACK_SIZE=2097152 \
    -o nobodywho_js.js
)

echo "==> patching nobodywho_js.js: defer _initialize + wait for pthread pool"
# _initialize() runs C++ static constructors. With pthreads, mutexes in
# the ctors use memory.atomic.wait32 which needs the pthread pool workers
# to be running. The pool workers are started asynchronously (new Worker)
# and need the event loop to tick. _initialize blocks the event loop, so
# the workers never start → deadlock. Fix: defer _initialize to a
# setTimeout so the event loop starts the workers first.
#
# We ALSO wait for the pthread pool to FULLY load (runDependencies → 0)
# before the factory resolves. The pool loads as a run-dependency that
# run() defers; if the factory resolves before it completes, the first
# inference's ggml threadpool pthread_create blocks waiting for pool
# workers that aren't ready — deadlocking in top-level-await code that
# never yields back to the event loop. Waiting here guarantees the pool
# is warm before any user inference call.
python3 -c "
import sys
path = sys.argv[1]
text = open(path).read()

def must_replace(text, old, new, label):
    if old not in text:
        sys.stderr.write('error: build patch did not match (emcc/wasm-bindgen drift?): '
                         + label + '. The artifact would build green but '
                         'deadlock/break at runtime — fix the pattern.\n')
        sys.exit(1)
    return text.replace(old, new)

# 1. Skip _initialize in initBindgen (runs sync, can't await the
#    setTimeout needed to let pthread pool workers start).
text = must_replace(text,
    'if (wasmExports[\"_initialize\"]) {\n    wasmExports[\"_initialize\"]();\n  }',
    '// _initialize deferred — see below',
    'skip sync _initialize in initBindgen')

# 2. After the main-thread createWasm + run(): yield so the pool workers
#    start, wait until the worker-loading run dependency clears, then run
#    _initialize. This keeps the event loop pumping (setTimeout macrotasks)
#    while the Emscripten pthread pool finishes loading.
text = must_replace(text,
    'wasmExports = await (createWasm());\n  run();',
    'wasmExports = await (createWasm());\n  run();\n'
    '  // Wait for the pthread pool to finish loading (runDependencies → 0).\n'
    '  for (let i = 0; i < 600 && runDependencies > 0; i++) {\n'
    '    await new Promise(r => setTimeout(r, 50));\n'
    '  }\n'
    '  if (wasmExports[\"_initialize\"]) {\n    await new Promise(r => setTimeout(r, 0));\n    wasmExports[\"_initialize\"]();\n  }',
    'defer _initialize until the pthread pool is ready')

# 3. Set the wasm-bindgen 'wasm' binding object in receiveInstance()
#    so it's available in pthread workers (not just the main thread).
#    Without this, JS callbacks from the inference thread hit
#    'Cannot read properties of null' because initBindgen (which sets
#    wasm = wasmExports) only runs on the main thread.
text = must_replace(text,
    'wasmExports = instance.exports;',
    'wasmExports = instance.exports;\n    wasm = wasmExports;',
    'set wasm binding in receiveInstance for pthread workers')

open(path, 'w').write(text)
" "$PKG_DIR/nobodywho_js.js"

# Some consumers expect the wasm under the bare name too. emcc post-link
# only writes _bg.wasm; mirror it.
cp "$PKG_DIR/nobodywho_js_bg.wasm" "$PKG_DIR/nobodywho_js.wasm"

echo
echo "==> Done. Outputs in $PKG_DIR/:"
ls -lh "$PKG_DIR" | sed 's/^/    /'
echo
echo "Smoke test:"
echo "  PATH=/opt/homebrew/bin:\$PATH node $JS_DIR/scripts/emscripten-smoke.mjs <embedding.gguf>"
