#!/usr/bin/env bash
# Build nobodywho-js's deployable artifacts under wasm32-unknown-emscripten.
#
# Produces nobodywho/js/pkg-bundler/ with:
#   nobodywho_js.js         — modularized Emscripten loader + library glue
#   nobodywho_js_bg.wasm    — wasm-bindgen processed wasm
#   nobodywho_js.wasm       — same wasm (mirrored under a second name some
#                              consumers expect)
#   library_bindgen.js      — kept around so debugging post-link is easy
#
# Prereqs (see ../README.md for setup details):
#   - walkingeyerobot's emscripten fork at /Users/user/git/emscripten-wbg
#     providing the -sWASM_BINDGEN setting (PR emscripten-core/emscripten#23493).
#   - stock wasm-bindgen-cli 0.2.121 at ~/.cargo/bin/wasm-bindgen — used by
#     em++ as the actual descriptor interpreter, controlled via $EM_WASM_BINDGEN.
#   - $LIBCLANG_PATH pointing at a libclang that bindgen can find (Apple's CLT
#     bin/lib works: /Library/Developer/CommandLineTools/usr/lib).
#   - pkg-bundler/pre.js present — the HEAP_DATA_VIEW lazy-getter shim that
#     emcc's --pre-js flag inlines into the loader's prologue. This file lives
#     in the repo's pkg-bundler/ skeleton because it's hand-written, not
#     regenerated by the build.
#
# Why post-link instead of letting emcc do it all in one shot:
#   rustc invokes em++ for the cdylib link with `-o ...wasm`, which makes
#   em++ emit only the .wasm (no JS loader). To produce the runnable bundle
#   we run em++ a SECOND time in `--post-link` mode against the wasm-bindgen
#   library output (already in emcc's temp dir from the cargo build), with
#   `-sMODULARIZE=1 -sEXPORT_ES6=1` to wrap the loader in a factory function.
#
# Why the sed patches: workarounds for codegen bugs in stock wasm-bindgen-cli
# 0.2.121 when targeting the emscripten module shape:
#   - HEAPU80()/HEAP320() — wasm-bindgen emits the typed-array getter form
#     used by the bundler target. Emscripten's runtime expects the plain
#     HEAPU8/HEAP32 globals (no parens). When upstream wasm-bindgen learns
#     to emit Emscripten-shaped globals, drop the substitutions.
#   - Model.__wrap / TokenStream.__wrap — wasm-bindgen's "constructor"
#     attribute generates a static-method call on the bare class. emcc wraps
#     classes onto `Module.*`, so the static-method call needs to be
#     redirected to `Module.Model.__wrap`. Same upstream fix applies.
#   - __wbg_terminated_addr / __wbg_called_abort — wasm-bindgen-cli
#     references these inside __wbg_call_guard without declaring them
#     anywhere. Without the `var` hoist Emscripten's JS compiler throws
#     ReferenceError before any user code runs.
#   - extraLibraryFuncs.push(...) — Emscripten's JS library compiler doesn't
#     auto-discover the $-prefixed helpers wasm-bindgen emits via
#     `addToLibrary({ '$foo': ... })`. We grep them out of library_bindgen.js
#     and push them onto extraLibraryFuncs so the JS compiler emits them.
#
# Outputs are in pkg-bundler/ ready for `node js/scripts/emscripten-smoke.mjs`,
# `js/examples/*.mjs`, or an npm publish via build-pkg.sh's package.json
# templating step (which is orthogonal to this script).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")"/../../.. && pwd)"   # repo root
JS_DIR="$ROOT/nobodywho/js"
PKG_DIR="$JS_DIR/pkg-bundler"
TARGET_DIR="$ROOT/nobodywho/target/wasm32-unknown-emscripten/release"

EMSDK_DIR="${EMSDK_DIR:-/Users/user/git/emscripten-wbg}"
EM_CONFIG="${EM_CONFIG:-$EMSDK_DIR/.emscripten}"
WASM_BINDGEN_BIN="${EM_WASM_BINDGEN:-$HOME/.cargo/bin/wasm-bindgen}"

if [[ ! -x "$EMSDK_DIR/emcc" ]]; then
  echo "error: emcc not found at $EMSDK_DIR/emcc" >&2
  echo "       Set EMSDK_DIR to walkingeyerobot's emscripten fork checkout." >&2
  exit 1
fi
if [[ ! -x "$WASM_BINDGEN_BIN" ]]; then
  echo "error: wasm-bindgen-cli not found at $WASM_BINDGEN_BIN" >&2
  echo "       cargo install wasm-bindgen-cli --version \$(bash $JS_DIR/scripts/wasm-bindgen-version.sh) --locked" >&2
  exit 1
fi
if [[ ! -f "$PKG_DIR/pre.js" ]]; then
  echo "error: $PKG_DIR/pre.js missing — needed as --pre-js input to emcc post-link." >&2
  exit 1
fi

# Emscripten's temp dir; emcc drops wasm-bindgen output here during the
# cargo-driven link step. We grab library_bindgen.js from this exact path
# in the post-link step below.
EMCC_TEMP="${EMCC_TEMP:-${TMPDIR:-/tmp}/emscripten_temp}"
EMCC_TEMP="${EMCC_TEMP%/}"  # strip trailing slash
mkdir -p "$EMCC_TEMP"

echo "==> cargo build --target wasm32-unknown-emscripten --release -p nobodywho-js"
rm -rf "$TARGET_DIR"
(
  cd "$ROOT/nobodywho"
  PATH="$EMSDK_DIR:$HOME/.rustup/toolchains/stable-aarch64-apple-darwin/bin:$HOME/.cargo/bin:/opt/homebrew/bin:$PATH" \
  EM_CONFIG="$EM_CONFIG" \
  EM_WASM_BINDGEN="$WASM_BINDGEN_BIN" \
  LIBCLANG_PATH="${LIBCLANG_PATH:-/Library/Developer/CommandLineTools/usr/lib}" \
  cargo build --release --target wasm32-unknown-emscripten -p nobodywho-js
)

# The cargo build only emits target/.../release/nobodywho_js.wasm. The
# matching library_bindgen.js (wasm-bindgen JS glue, addToLibrary form) gets
# left behind in $EMCC_TEMP/bindgen_out/ by em++'s -sWASM_BINDGEN handler.
EMCC_BINDGEN_OUT="$(ls -dt "$EMCC_TEMP"*/bindgen_out 2>/dev/null | head -n1 || true)"
if [[ -z "$EMCC_BINDGEN_OUT" || ! -f "$EMCC_BINDGEN_OUT/library_bindgen.js" ]]; then
  # Some Emscripten versions don't suffix the temp dir; fall back to the
  # un-suffixed location.
  EMCC_BINDGEN_OUT="$EMCC_TEMP/bindgen_out"
fi
if [[ ! -f "$EMCC_BINDGEN_OUT/library_bindgen.js" ]]; then
  echo "error: library_bindgen.js not found under $EMCC_TEMP" >&2
  echo "       Looked at: $EMCC_BINDGEN_OUT/library_bindgen.js" >&2
  echo "       Did the cargo build actually run em++ with -sWASM_BINDGEN?" >&2
  exit 1
fi
echo "==> using $EMCC_BINDGEN_OUT/library_bindgen.js"

echo "==> copying artifacts into pkg-bundler/"
mkdir -p "$PKG_DIR"
cp "$EMCC_BINDGEN_OUT/library_bindgen.js" "$PKG_DIR/library_bindgen.js"
cp "$TARGET_DIR/nobodywho_js.wasm"        "$PKG_DIR/nobodywho_js_bg.wasm"

echo "==> applying sed patches to library_bindgen.js"
# See block comment at top of file for why each substitution is needed.
/usr/bin/sed -i.bak \
  -e 's/HEAPU80()/HEAPU8/g' \
  -e 's/HEAP320()/HEAP32/g' \
  -e 's/Model\.__wrap/Module.Model.__wrap/g' \
  -e 's/TokenStream\.__wrap/Module.TokenStream.__wrap/g' \
  "$PKG_DIR/library_bindgen.js"

/usr/bin/sed -i.bak2 \
  's|        function __wbg_call_guard() {$|        var __wbg_terminated_addr; var __wbg_called_abort;\n        function __wbg_call_guard() {|' \
  "$PKG_DIR/library_bindgen.js"

echo "==> appending extraLibraryFuncs.push(...) for \$-prefixed helpers"
FUNCS=$(
  grep -oE "'\\\$[a-zA-Z_0-9]+'" "$PKG_DIR/library_bindgen.js" \
    | grep -v '__deps' \
    | sort -u \
    | tr '\n' ',' \
    | sed 's/,$//'
)
if [[ -z "$FUNCS" ]]; then
  echo "warning: no \$-prefixed addToLibrary helpers found — script grep may be stale" >&2
else
  echo "extraLibraryFuncs.push($FUNCS);" >> "$PKG_DIR/library_bindgen.js"
fi
rm -f "$PKG_DIR/library_bindgen.js".bak*

echo "==> em++ --post-link to build nobodywho_js.js"
(
  cd "$PKG_DIR"
  PATH="$EMSDK_DIR:/opt/homebrew/bin:$PATH" \
  EM_CONFIG="$EM_CONFIG" \
  "$EMSDK_DIR/emcc" \
    nobodywho_js_bg.wasm \
    --post-link \
    --js-library library_bindgen.js \
    --pre-js pre.js \
    -sALLOW_MEMORY_GROWTH=1 \
    -sMAXIMUM_MEMORY=4GB \
    -sMODULARIZE=1 \
    -sEXPORT_ES6=1 \
    -sEXPORT_NAME='createNobodyWhoModule' \
    -sERROR_ON_UNDEFINED_SYMBOLS=0 \
    -sINVOKE_RUN=0 \
    -Wno-undefined \
    -O1 \
    -o nobodywho_js.js
)

# Some consumers expect the wasm under the bare name too. emcc post-link
# only writes _bg.wasm; mirror it.
cp "$PKG_DIR/nobodywho_js_bg.wasm" "$PKG_DIR/nobodywho_js.wasm"

echo
echo "==> Done. Outputs in $PKG_DIR/:"
ls -lh "$PKG_DIR" | sed 's/^/    /'
echo
echo "Smoke test:"
echo "  PATH=/opt/homebrew/bin:\$PATH node $JS_DIR/scripts/emscripten-smoke.mjs <embedding.gguf>"
echo "  PATH=/opt/homebrew/bin:\$PATH node $JS_DIR/scripts/path-b-smoke.mjs   [chat.gguf]"
