/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare namespace SamplerPresets {
  /** Get the default sampler configuration. */
  export function defaultSampler(): SamplerConfig
  /** Create a DRY sampler preset to reduce repetition. */
  export function dry(): SamplerConfig
  /** Create a sampler with a custom grammar constraint. */
  export function grammar(grammar: string): SamplerConfig
  /** Create a greedy sampler (always picks most probable token). */
  export function greedy(): SamplerConfig
  /** Create a sampler configured for JSON output generation. */
  export function json(): SamplerConfig
  /** Create a sampler with temperature scaling. */
  export function temperature(temperature: number): SamplerConfig
  /** Create a sampler with top-k filtering only. */
  export function topK(topK: number): SamplerConfig
  /** Create a sampler with nucleus (top-p) sampling. */
  export function topP(topP: number): SamplerConfig
}

export declare class Chat {
  /** Create a new chat session. */
  constructor(model: Model, systemPrompt?: string | undefined | null, contextSize?: number | undefined | null, templateVariables?: Record<string, boolean> | undefined | null, tools?: Array<Tool> | undefined | null, sampler?: SamplerConfig | undefined | null)
  /** Send a message and get a token stream for the response. */
  ask(message: string): TokenStream
  /** Stop the current generation. */
  stopGeneration(): void
  /** Reset the chat context with a new system prompt and tools. */
  resetContext(systemPrompt?: string | undefined | null, tools?: Array<Tool> | undefined | null): Promise<void>
  /** Reset the chat history, keeping the system prompt and tools. */
  resetHistory(): Promise<void>
  /** Get the current chat history as an array of message objects. */
  getChatHistory(): Promise<Array<any>>
  /** Set the chat history from an array of message objects. */
  setChatHistory(messages: Array<any>): Promise<void>
  /** Get the current system prompt. */
  getSystemPrompt(): Promise<string | null>
  /** Set the system prompt. */
  setSystemPrompt(systemPrompt?: string | undefined | null): Promise<void>
  /** Set the tools available to the model. */
  setTools(tools: Array<Tool>): Promise<void>
  /** Set a template variable. */
  setTemplateVariable(name: string, value: boolean): Promise<void>
  /** Get all template variables. */
  getTemplateVariables(): Promise<Record<string, boolean>>
  /** Set the sampler configuration. */
  setSamplerConfig(sampler: SamplerConfig): Promise<void>
  /** Get the current sampler configuration as a JSON string. */
  getSamplerConfigJson(): Promise<string>
}

export declare class CrossEncoder {
  /** Create a new cross-encoder for ranking documents by relevance. */
  constructor(model: Model, contextSize?: number | undefined | null)
  /** Rank documents by relevance to a query. Returns similarity scores. */
  rank(query: string, documents: Array<string>): Promise<Array<number>>
  /**
   * Rank documents and return them sorted by descending relevance.
   * Returns an array of [document, score] pairs.
   */
  rankAndSort(query: string, documents: Array<string>): Promise<Array<Array<string>>>
}

export declare class Encoder {
  /** Create a new encoder for generating text embeddings. */
  constructor(model: Model, contextSize?: number | undefined | null)
  /** Encode text into an embedding vector. */
  encode(text: string): Promise<Array<number>>
}

export declare class Model {
  /** Load a GGUF model from disk. */
  static load(modelPath: string, useGpu: boolean, imageModelPath?: string | undefined | null): Promise<Model>
  /** Check if a discrete GPU is available. */
  static hasDiscreteGpu(): boolean
}

export declare class SamplerBuilder {
  /** Create a new SamplerBuilder to construct a custom sampler chain. */
  constructor()
  /** Keep only the top K most probable tokens. */
  topK(topK: number): SamplerBuilder
  /** Keep tokens whose cumulative probability is below top_p. */
  topP(topP: number, minKeep: number): SamplerBuilder
  /** Keep tokens with probability above min_p * (probability of most likely token). */
  minP(minP: number, minKeep: number): SamplerBuilder
  /** Apply temperature scaling to the probability distribution. */
  temperature(temperature: number): SamplerBuilder
  /** XTC sampler that probabilistically excludes high-probability tokens. */
  xtc(xtcProbability: number, xtcThreshold: number, minKeep: number): SamplerBuilder
  /** Typical sampling: keeps tokens close to expected information content. */
  typicalP(typP: number, minKeep: number): SamplerBuilder
  /** Apply a grammar constraint to enforce structured output. */
  grammar(grammar: string, triggerOn: string | undefined | null, root: string): SamplerBuilder
  /** DRY (Don't Repeat Yourself) sampler to reduce repetition. */
  dry(multiplier: number, base: number, allowedLength: number, penaltyLastN: number, seqBreakers: Array<string>): SamplerBuilder
  /** Apply repetition penalties to discourage repeated tokens. */
  penalties(penaltyLastN: number, penaltyRepeat: number, penaltyFreq: number, penaltyPresent: number): SamplerBuilder
  /** Sample from the probability distribution (weighted random selection). */
  dist(): SamplerConfig
  /** Always select the most probable token (deterministic). */
  greedy(): SamplerConfig
  /** Use Mirostat v1 algorithm for perplexity-controlled sampling. */
  mirostatV1(tau: number, eta: number, m: number): SamplerConfig
  /** Use Mirostat v2 algorithm for perplexity-controlled sampling. */
  mirostatV2(tau: number, eta: number): SamplerConfig
}

export declare class SamplerConfig {
  /** Serialize the sampler configuration to a JSON string. */
  toJson(): string
  /** Deserialize a sampler configuration from a JSON string. */
  static fromJson(jsonStr: string): SamplerConfig
}

export declare class TokenStream {
  /** Get the next token. Returns null when generation is complete. */
  nextToken(): Promise<string | null>
  /** Wait for the full response to complete and return it. */
  completed(): Promise<string>
}

export declare class Tool {
  /**
   * Create a tool that the model can call during inference.
   *
   * The callback receives the tool arguments as a JSON string and must return
   * a result as a string. The callback is invoked from the inference thread
   * when the model calls this tool.
   */
  constructor(name: string, description: string, jsonSchema: string, callback: (argsJson: string) => string)
}

/** Compute the cosine similarity between two vectors. */
export declare function cosineSimilarity(a: Array<number>, b: Array<number>): number
