name: "Docs"
on:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true
permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write
jobs:
  deploy-pages:
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        working-directory: ./docs
        run: npm ci

      - name: Build documentation
        working-directory: ./docs
        run: npm run build

      - name: Deploy to cloudflare pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./docs/build/ --project-name=nobodywho-docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
