name: "Docs"
on:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true
permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write
jobs:
  deploy-pages:
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - uses: actions/checkout@v5

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.10.18

      - name: Build documentation
        working-directory: ./docs
        run: quarto render

      - name: Deploy to cloudflare pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./docs/_site/ --project-name=nobodywho-docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
