name: "Lint & Format checks"
on: workflow_call

jobs:
  lint:
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Setup rust toolchain"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: "Cache Rust build"
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: nobodywho
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: "Install distro dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev cmake libshaderc-dev libvulkan-dev glslc

      - name: "Run rustfmt check"
        working-directory: "./nobodywho"
        run: cargo fmt --all --check

      - name: "Run clippy check"
        working-directory: "./nobodywho/core"
        run: cargo clippy --no-deps -- -D warnings
