name: "python_ci"

on:
  workflow_call

permissions:
  contents: read

jobs:
  linux-build:
    runs-on: ubuntu-24.04
    strategy: 
      fail-fast: false
      matrix:
        profile:
          - "release"
        target:
          - "x86_64-unknown-linux-gnu"
        
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - run: pip install maturin
      - name: "Install distro dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev cmake libshaderc-dev libvulkan-dev glslc
      - name: "Build linux python wheel"
        run: maturin build --verbose ${{ matrix.profile == 'release' && '--release' || '' }} --locked
        working-directory: ./nobodywho/python
      #- run: curl -sSf https://sshx.io/get | sh -s run
     
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: nobodywhopython-0.1.0-cp38-abi3-manylinux_2_38_x86_64.whl
          path: ./nobodywho/target/wheels/nobodywhopython-0.1.0-cp38-abi3-manylinux_2_38_x86_64.whl
        
  windows-build:
    runs-on: windows-latest
    strategy: 
      fail-fast: false
      matrix: 
        target:
          - "x86_64-pc-windows-msvc"
        profile:
          - "release"
    env:
      RUSTFLAGS: >-
        -l Advapi32
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - run: pip install maturin
      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.2.5
        with:
          vulkan_version: 1.3.296.0
          cache: true
          install_runtime: true
          stripdown: true
      - name: "Build windows python wheel"
        run: |
          mv ./nobodywho/* C:/
          cd C:/
          cd python
          maturin build --verbose ${{ matrix.profile == 'release' && '--release' || '' }} --locked --target ${{ matrix.target }}
      - name: "Upload wheel artifact"
        uses: actions/upload-artifact@v4
        with:
          name: nobodywhopython-0.1.0-cp38-abi3-win_amd64.whl
          path: C:\target\wheels\nobodywhopython-0.1.0-cp38-abi3-win_amd64.whl


  mac-os-build:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        target:
          - "x86_64-apple-darwin"
          - "aarch64-apple-darwin"
        profile:
          - "release"
    env:
      CARGO_BUILD_TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - run: rustup target add ${{ matrix.target }}
      - uses: mlugg/setup-zig@v2
      - run: brew install maturin
      - name: "Build macos python wheel"
        run: maturin build --verbose ${{ matrix.profile == 'release' && '--release' || '' }} --locked --target ${{ matrix.target }} --zig
        working-directory: ./nobodywho/python
        
      #- run: curl -sSf https://sshx.io/get | sh -s run
      - name: "Rename built files"
        run: cp .nobodywho/target/wheels/nobodywhopython* ./nobodywhopython-${{ matrix.target }}-${{ matrix.profile }}.whl
      
      - name: "Upload build artifact"
        uses: actions/upload-artifact@v4
        with:
          name: nobodywhopython-${{ matrix.target }}-${{ matrix.profile }}.whl
          path: ./nobodywhopython-${{ matrix.target }}-${{ matrix.profile }}.whl
      
  


  linux-pip-install-test:
    needs: [linux-build]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - run: pip install maturin
      - name: "Install distro dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev cmake libshaderc-dev libvulkan-dev glslc
      - name: "Download wheel"
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      - name: Install whell
        run: |
          python3 -m venv maturinvenv
          source ./maturinvenv/bin/activate
          pip install artifacts/nobodywhopython-0.1.0-cp38-abi3-manylinux_2_38_x86_64.whl
      



  mac-os-pip-install-test:
    needs: [mac-os-build]
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        target:
          - "x86_64-apple-darwin"
          - "aarch64-apple-darwin"
        profile:
          - "release"
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      
      - name: "Download wheel"
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      - name: Install whell
        run: |
          python3 -m venv maturinvenv
          source ./maturinvenv/bin/activate
          pip install artifacts/nobodywhopython-${{ matrix.target }}-${{ matrix.profile }}.whl
      

  windows-pip-install-test:
    runs-on: windows-latest
    needs: [windows-build]
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - run: pip install maturin
      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.2.5
        with:
          vulkan_version: 1.3.296.0
          cache: true
          install_runtime: 
      - name: "Download wheel"
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Install wheel
        run: |
          python -m venv maturinvenv
          maturinvenv\Scripts\activate
          pip install artifacts/nobodywhopython-0.1.0-cp38-abi3-win_amd64.whl

      



      
