name: "Test npm publish"

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  test-publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
        
      - name: "Verify Login"
        working-directory: ./nobodywho/react-native
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: "Publish to npm"
        working-directory: ./nobodywho/react-native
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
